# Rustfmt configuration for pdf_oxide
# See https://rust-lang.github.io/rustfmt/ for all options

# Edition
edition = "2021"

# Line width
max_width = 100
comment_width = 80

# Indentation
tab_spaces = 4
hard_tabs = false

# Imports
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
reorder_imports = true
reorder_modules = true

# Formatting
fn_single_line = false
where_single_line = false
force_explicit_abi = true
format_code_in_doc_comments = true
format_macro_matchers = true
format_macro_bodies = true
format_strings = true
normalize_comments = true
normalize_doc_attributes = true
wrap_comments = true

# Function calls
fn_call_width = 80
fn_params_layout = "Tall"
overflow_delimited_expr = true

# Structs and enums
struct_field_align_threshold = 0
enum_discrim_align_threshold = 0

# Control flow
control_brace_style = "AlwaysSameLine"
match_arm_blocks = true
match_block_trailing_comma = true

# Whitespace
blank_lines_upper_bound = 2
blank_lines_lower_bound = 0
use_small_heuristics = "Default"

# Trailing comma
trailing_comma = "Vertical"

# Newlines
newline_style = "Unix"
use_field_init_shorthand = true
use_try_shorthand = true

# Chains
chain_width = 60
chains_overflow_last = true

# Style
unstable_features = false
version = "Two"
